[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://opendart.fss.or.kr/api/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/stock-api/getStockPriceInfo/"
  to = "http://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService/getStockPriceInfo"
  status = 200
  force = true

[[redirects]]
  from = "/stock-api/*"
  to = "http://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
